name: 'Close stale issues'
on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          any-of-labels: needs-info
          labels-to-remove-when-unstale: needs-info
